apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixmix-deployment
  namespace: pixmix-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixmix
  template:
    metadata:
      labels:
        app: pixmix
    spec:
      containers:
        - name: pixmix
          image: your_docker_image:latest # Replace with your built Docker image name
          ports:
            - containerPort: 80
...
apiVersion: v1
kind: Service
metadata:
  name: pixmix-service
  namespace: pixmix-namespace
spec:
  selector:
    app: pixmix
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Use NodePort if LoadBalancer is not available
