name: CI
on:
     push:
        branches:
             - master
jobs:
    Greet-User:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Greet User 
              run: | 
                echo "welcome"
            - name: "logs into Docker hub Account"  
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: "build the image" 
              env:
                image name: test-image # image name variable
                version: 1.0.0 # image version variable
                username: dapper01
                run: |
                   docker build -t $username/$image name:$version .
                   docker push $username/$image_name:$version 
                  
                           