name: CI
on:
     push:
        branches:
             - master
jobs:
    Greet-User:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Greet User 
              run: | 
                   user="john Doe"
                   echo "hello $user"
                  
                           